language: c

before_install:
    - cd $TRAVIS_BUILD_DIR
    - git clone https://github.com/samtools/htslib.git
    - cd htslib
    - make
    - cd $TRAVIS_BUILD_DIR


script:
    - cd test/unit/
    - make
